### ISSUE TITLE
CustomerSearch on Phone

### ISSUE THREAD

**Issue by dv14asr** [softwerkab/fortnox-csharp-api-sdk#289]
When trying to use CustomerSearch on Phone im running into the error 
`Fortnox.SDK.Exceptions.FortnoxApiException: 'Request failed: Ogiltig parameter i anropet.'`

This is the current code im trying. All other parameters seems to work but as soon as im trying to search by phone it throws exception

`
                var customerSubset = await CustomerConnector.FindAsync(new CustomerSearch()
                {
                    Phone1 = "0704455667"
                });
`

Has anyone stumbled across the same issue?

**Comment by adamelfstrom** [comment]
It seems the search parameter `Phone1` is supposed to be `Phone`. This is a bug in the SDK.
https://apps.fortnox.se/apidocs#tag/CustomersResource/operation/list_CustomersResource

**Comment by adamelfstrom** [comment]
Hi, this field has been added to the SDK in v 4.3.17
