### ISSUE TITLE
Missing Order.TotalToPay field - is the SDK up to date with the API?

### ISSUE THREAD

**Issue by lafar6502** [softwerkab/fortnox-csharp-api-sdk#290]
Hi
According to Fortnox API documentation, there should be Order.TotalToPay field

https://apps.fortnox.se/apidocs#tag/OrdersResource/operation/create_OrdersResource

But it's missing in SDK Order class. SDK not updated with most recent API, or some other problem?
BTW is there an API changelog for Fortnox? I tried to find out when the field was introduced, but no information about that seems to be available.
If the SDK is not up to date with recent API changes, when can we expect a next version?
Thanks
RG

**Comment by adamelfstrom** [comment]
Hi, this field has been added to the SDK in v 4.3.17
